name: Firebase Hosting

on:
  push:
    branches:
      - firebase

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_MY_UNETI }}"
          expires: 30d
          projectId: khien-uneti
          channelId: preview
