name: Firebase Hosting

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.PAT_TOKEN }}
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_MY_UNETI }}"
          expires: 30d
          projectId: khien-uneti
          channelId: preview

      - name: "Echo Preview URL"
        run:
          echo "Preview URL: ${{ steps.firebaseDeploy.outputs.details_url }}"
